version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - ENVNAME=Dev
      - DB_HOST=db
      - DB_NAME=devopsdb
      - DB_USER=root
      - DB_PASS=password
    depends_on:
      - db
    volumes:
      - ./webapp:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: devopsdb
    volumes:
      - dbdata:/var/lib/mysql
      - ./devops-demo-1.1.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  dbdata:
